### ISSUE TITLE
Run ECIES Profile B Throw Exception

### ISSUE THREAD

**Issue by helloworld666** [mitshell/CryptoMobile#9]
Thank you for providing the program, ECIES Profile A runs perfectly. However, using the test data of C.4.4 in the 3GPP 33501-g00.doc document, the following code is executed:
from CryptoMobile.ECIES import *
hn_privkey = bytes.fromhex('F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA')
hn = ECIES_HN(hn_privkey, profile='B')

The program throws an exception:
in _handle_key_loading_error raise ValueError("Could not deserialize key data.")

**Comment by p1-bmu** [comment]
Thanks for your feedback.
Can you please indicate on which OS you are ? Which Python version you are using ? Which version of the crypto backend (cryptography) you are using ?
And can you provide the complete stack trace leading to this exception ?

**Comment by helloworld666** [comment]
OS is mac os x 10.15.4;python version is 3.8.2; the encryption library is cryptography 2.9.2.
complete stack trace:
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/Develop/SUCI/ProfileBPlain.py", line 4, in <module>
    hn = ECIES_HN(hn_privkey, profile='B')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/CryptoMobile/ECIES.py", line 112, in __init__
    self.EC = ECDH_SECP256R1(loc_privkey=hn_priv_key)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/CryptoMobile/EC.py", line 92, in __init__
    self.PrivKey = serialization.load_der_private_key(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 28, in load_der_private_key
    return backend.load_der_private_key(data, password)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1149, in load_der_private_key
    return self._load_key(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1324, in _load_key
    self._handle_key_loading_error()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1382, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
Thank you very much!

**Comment by p1-bmu** [comment]
test vectors for profile B are implemented successfully here: https://github.com/mitshell/CryptoMobile/blob/00342122915e5246888ffb142c496e609a9048e8/test/test_ECIES.py#L74
Your issue seems to be that you try to load a private key directly into the SECP256R1 handler, what is not possible. SECP256R1 does not support loading of a private key independently / directly, you can use this specific call to load a private key in the ECIES_HN side: https://github.com/mitshell/CryptoMobile/blob/00342122915e5246888ffb142c496e609a9048e8/test/test_ECIES.py#L90

**Comment by helloworld666** [comment]
Yes! it fits exactly the input and output of 3GPP ECIES test data. It turned out that there was a problem with my program code. Thank you again for your help.
